# Generated by Django 4.2.8 on 2024-03-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pulisher',
            new_name='Publisher',
        ),
    ]
